run: |
  git config --global user.email "github-actions@github.com"
  git config --global user.name "GitHub Actions"

  git clone https://oauth2:${HF_TOKEN}@huggingface.co/spaces/kadmsdfgsdfg/Resume-Intelligence-Analyser /tmp/hf

  rsync -av --delete \
    --exclude ".git" \
    --exclude ".github" \
    ./ /tmp/hf/

  cd /tmp/hf

  git add .

  git commit -m "Auto Deploy" || echo "No changes"

  git push